import Head from "next/head";
import GarapinAppBar from "@/components/GarapinAppBar";
import {useEffect, useState} from 'react'
import Box from "@mui/material/Box";
import GarapinFooter from "@/components/GarapinFooter";
import Typography from "@mui/material/Typography";
import RoundedImage from "@/components/RoundedImage";
import * as React from "react";
import {alpha, styled} from "@mui/material/styles";
import InputBase from "@mui/material/InputBase";
import Button from "@mui/material/Button";

const Register = styled('div')(({theme}) => ({
    position: 'relative',
    borderRadius: theme.shape.borderRadius,
    backgroundColor: theme.palette.common.white,
    '&:hover': {
        backgroundColor: alpha(theme.palette.common.white, 0.8),
    },
    width: '100%',
    [theme.breakpoints.up('sm')]: {
        width: 'auto',
    },
}));

const StyledInputBase = styled(InputBase)(({theme}) => ({
    color: '#713F97',
    '& .MuiInputBase-input': {
        padding: theme.spacing(1, 1, 1, 3),
        transition: theme.transitions.create('width'),
        width: '100%',
        [theme.breakpoints.up('sm')]: {
            width: '50ch',
        },
    },
}));

export default function LandingPage() {
    return (
        <>
            <Head>
                <title>Garapin</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Box className="flex flex-col">
                    <GarapinAppBar/>
                    <Box className="flex flex-col items-center justify-between pt-20 pb-20"
                         sx={{backgroundColor: '#F8F4F9'}}>
                        <Typography variant="h4" color="#713F97" className="pb-20" fontWeight="bold">Copy Message 1:
                            Semudah 1,2,3.</Typography>
                        <Box className="flex flex-row justify-around pl-96 pr-96">
                            <Box className="flex flex-col items-center justify-center" sx={{width: 200}}>
                                <RoundedImage
                                    src="https://edit.co.uk/uploads/2016/12/Image-1-Alternatives-to-stock-photography-Thinkstock.jpg"
                                    alt="Rounded Image"/>
                                <Typography variant="h5" color="text.primary" className="pt-3"
                                            fontWeight="bold">Cari</Typography>
                                <Typography variant="body1" color="text.primary" align="center">Lorem ipsum dolor sit
                                    amet consectetur. Volutpat posuere egestas.</Typography>
                            </Box>
                            <Box className="flex flex-col items-center justify-center" sx={{width: 200}}>
                                <RoundedImage
                                    src="https://edit.co.uk/uploads/2016/12/Image-1-Alternatives-to-stock-photography-Thinkstock.jpg"
                                    alt="Rounded Image"/>
                                <Typography variant="h5" color="text.primary" className="pt-3"
                                            fontWeight="bold">Buat</Typography>
                                <Typography variant="body1" color="text.primary" align="center">Lorem ipsum dolor sit
                                    amet consectetur. Volutpat posuere egestas.</Typography>
                            </Box>
                            <Box className="flex flex-col items-center justify-center" sx={{width: 200}}>
                                <RoundedImage
                                    src="https://edit.co.uk/uploads/2016/12/Image-1-Alternatives-to-stock-photography-Thinkstock.jpg"
                                    alt="Rounded Image"/>
                                <Typography variant="h5" color="text.primary" className="pt-3"
                                            fontWeight="bold">Kirim</Typography>
                                <Typography variant="body1" color="text.primary" align="center">Lorem ipsum dolor sit
                                    amet consectetur. Volutpat posuere egestas.</Typography>
                            </Box>
                        </Box>
                    </Box>
                    <Box className="flex flex-row items-center justify-between pt-20 pb-20 pl-80 pr-80"
                         sx={{backgroundColor: '#F8F4F9'}}>
                        <img
                            src="https://edit.co.uk/uploads/2016/12/Image-1-Alternatives-to-stock-photography-Thinkstock.jpg"
                            alt="Image with stock photos"/>
                        <Box className="max-w-sm">
                            <Typography variant="h4" color="#713F97" fontWeight="bold" className="pb-5">Lebih dari
                                Sekadar Direktori Usaha</Typography>
                            <Typography variant="body1" color="text.primary">Lorem ipsum dolor sit amet consectetur.
                                Scelerisque fusce gravida et risus facilisis. Dapibus nascetur purus et ac. Nec euismod
                                amet enim scelerisque venenatis. At sem purus arcu et egestas. Velit aenean et sed cras
                                habitant morbi. Cursus urna tellus pellentesque vestibulum aliquam aenean. Odio libero
                                senectus pharetra convallis lacus. Maecenas sed sed mattis pulvinar. Vulputate at dui
                                iaculis lectus convallis.</Typography>
                        </Box>
                    </Box>
                    <Box className="flex flex-row items-center justify-between pt-20 pb-20 pl-80 pr-80"
                         sx={{backgroundColor: '#FFFFFF'}}>
                        <Box className="max-w-sm">
                            <Typography variant="h4" color="#713F97" fontWeight="bold" className="pb-5">Dalam Sorotan
                                Media</Typography>
                            <Typography variant="body1" color="text.primary">Lorem ipsum dolor sit amet consectetur.
                                Scelerisque fusce gravida et risus facilisis. Dapibus nascetur purus et ac. Nec euismod
                                amet enim scelerisque venenatis. At sem purus arcu et egestas. Velit aenean et sed cras
                                habitant morbi. Cursus urna tellus pellentesque vestibulum aliquam aenean. Odio libero
                                senectus pharetra convallis lacus. Maecenas sed sed mattis pulvinar. Vulputate at dui
                                iaculis lectus convallis.</Typography>
                        </Box>
                        <img src="/daily_social_logo.png" alt="Daily Social Logo"/>
                        <img src="/startup4industries_logo.png" alt="Startup 4 Industries Logo"/>
                    </Box>
                    <Box className="flex flex-col items-center justify-around pt-20 pb-20 pl-80 pr-80"
                         sx={{backgroundColor: '#F8F4F9'}}>
                        <Typography variant="h4" color="#713F97" className="pb-20" fontWeight="bold">Mudahkan Produksi
                            Usahamu
                            Bersama Garapin</Typography>
                        <Typography variant="body1" color="text.primary" className="pb-20">Lorem ipsum dolor sit amet
                            consectetur. Scelerisque fusce gravida et risus facilisis. Dapibus nascetur purus et ac. Nec
                            euismod amet enim scelerisque venenatis. At sem purus arcu et egestas. Velit aenean et sed
                            cras habitant morbi. Cursus urna tellus pellentesque vestibulum aliquam aenean.</Typography>
                        <Register>
                            <StyledInputBase
                                placeholder="email@perusahaan-anda.co.id"
                                inputProps={{'aria-label': 'search'}}
                                onSubmit={(e) => {}}
                            />
                            <Button variant="contained" color="primary" className="ml-5">Daftar sekarang</Button>
                        </Register>
                    </Box>
                    <GarapinFooter/>
                </Box>
            </main>
        </>
    )
}